spring:
  application:
    name: security
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: -hongjing123
    url: jdbc:postgresql://127.0.0.1:5432/super_boot?currentSchema=public
server:
  port: 8080


